# 7장. 오류 처리

> 이 내용은 로버트 C. 마틴 저자님의 클린코드 책의 내용을 가져온 것입니다.

깨끗한 코드는 읽기도 좋아야 하지만 안정성도 높아야 한다. 오류 처리를 프로그램 논리와 분리해서 독자적인 사안으로 고려하면 튼튼하고 깨끗한 코드를 작성할 수 있다. 오류 처리를 프로그램 논리와 분리하면 독립적인 추론이 가능해지며 코드 유지보수성도 크게 높아진다.

### 오류 코드보다 예외를 사용해라.

```java
public class DeviceController {
  public void sendShutDown() {
    DeviceHandle handle = getHandle(DEV1);
    // 디바이스 상태를 점검한다.
    if (handle != DeviceHandle.INVALID) {
      // 레코드 필드에 디바이스 상태를 저장한다.
      retrieveDeviceRecord(handle);
      // 디바이스가 일시정지 상태가 아니라면 종료한다.
      if (record.getStatus() != DEVICE_SUSPENDED) {
        pauseDevice(handle);
        clearDeviceWorkQueue(handle);
        closeDevice(handle);
      } else {
        logger.log('Device suspended. Unable to shut down');
      }
    } else {
      logger.log('Invalid handle for: ' + DEV1.toString());
    }
  }
}
```

위 코드에서 getHandle(DEV1), record.getStatus()를 비교하는 로직을 보면 else 블록으로 넘어가면 에러 메세지를 로깅하고 있다. 위 코드의 문제점은 함수를 호출한 즉시 에러 처리를 하지 않기 때문에 코드가 복잡해져 이해하기가 어렵다.

위 코드를 `tryToShutDown` 이라는 메서드로 빼놓고 try-catch를 통해 예외를 처리해보도록 하자. else를 통해 분기처리를 하는 것 보다 예외를 던져서 처리하는 것이 깔끔하고 좋기 때문이다.

```java
public class DeviceController {
  public void sendShutDown() {
    try {
      tryToShutDown();
    } catch (DeviceShutDownError e) {
      logger.log(e);
    }
  }

  private void tryToShutDown() throws DeviceShutDownError {
    DeviceHandle handle = getHandle(DEV1);
    DeviceRecord record = retrieveDeviceRecord(handle);

    pauseDevice(handle);
    clearDeviceWorkQueue(handle);
    closeDevice(handle);
  }

  private DeviceHandle getHandle(DeviceId id) {
    ...
    throw new DeviceShutDownError('Invalid handle for: ' + id.toString());
    ...
  }
}
```

위의 코드보다 확실히 좋은점은 일단 보기만 해도 완전 깔끔해졌고, 디바이스를 종료하는 알고리즘과 오류를 처리하는 알고리즘을 분리했기 때문에 코드 품질도 좋아졌다.

<br>

### Try-Catch-Finally 문부터 작성하자.

> 예외가 발생할 경우가 있는 코드를 작성할 때는 try-catch로 시작하는 것이 좋다.

예를 들어 파일이 없는 경우에 예외를 던지는지 알아보는 단위테스트 코드를 작성해보도록 하자.

```java
@Test(expected = StorageException.class)
public void retrieveSectionShouldThrowOnInvalidFileName() {
  sectionStore.retrieveSection('Invalid - file');
}

public List<RecordedGrip> retrieveSection(String sectionName) {
  // 실제로 구현할 때까지 비어있는 더미를 반환한다.
  return new ArrayList<RecordedGrip>();
}
```

위의 코드를 보면 예외를 던지는 로직이 없기 때문에 단위 테스트는 실패하게 된다. 그래서 일부러 잘못된 파일 접근을 시도하게 구현을 변경해보면?

```java
public List<RecordedGrip> retrieveSection(String sectionName) {
  try {
    FileInputStream stream = new FileInputStream(sectionName);
  } catch (Exception e) {
    throw new StorageException('retrieval error', e);
  }
  return new ArrayList<RecordedGrip>();
}
```

코드가 예외를 던지기 때문에 테스트가 성공하게 된다. 그리고 이 시점에서 추가적으로 리팩터링이 가능해진다.

```java
public List<RecordedGrip> retrieveSection(String sectionName) {
    try {
        FileInputStream stream = new FileInputStream(sectionName);
        stream.close();
    } catch (FileNotFoundException e) {
        throw new StorageException("retrieval error", e);
    }
    return new ArrayList<RecordedGrip>();
}
```

- `FileInputStream stream = new FileInputStream(sectionName)`과 `stream.close()` 사이에 stream을 읽어와서 처리하는 로직들을 넣을 수 있는 범위를 만들어 준다. 저 사이에 추가된 로직들은 예외가 발생하지 않는다고 생각한다.
- 파일이 없으면 `FileNotFoundException이` 발생하기 때문에 Exception 범위를 줄여준다.

<br>

### 미확인(unchecked) 예외를 사용해라.

일단 먼저 미확인 예외가 무엇인지에 대해서 알아봐야 할 것 같다. Java에서 예외는 크게 `Checked Exception`과 `Unchecked Exception`으로 구분이 된다.

#### Checked Exception

- RuntimeException을 상속하지 않는 클래스
- 컴파일 시점에 컴파일러에서 확인하는 예외
- 반드시 에러 처리를 해야하는 특징을 가지고 있다.

예를 들어 다음과 같은 코드가 있다고 가정해보자.

```java
public class CheckedException {
  public static void main(String[] args) {
    try {
      File file = new File('examle.txt');
      Scanner scanner = new Scanner(file);
      while (scanner.hasNextLine()) {
        String line = scanner.nextLine();
        System.out.println('line = ' + line);
      }
      scanner.close();
    } catch (FileNotFoundException e) {
      System.out.println('An error occurred while reading the file:' + e.getMessage());
    }
  }
}
```

example.txt라는 파일을 읽어오는 코드인데 실제로 example.txt라는 파일은 존재하지 않기 때문에 문제가 있는 코드다. 그래서 example.txt 파일을 읽으려고 하면 FileNotFoundException을 진행하게 된다.

그렇다면 왜 checked exception을 사용하지 말라고 할까?

```java
public void a() throws FileNotFoundException {
  b();
}

private void b() throws FileNotFoundException {
    c();
}

private void c() throws FileNotFoundException {
    FileInputStream stream = new FileInputStream("fileName");
}
```

a가 b를 부르고, b가 c를 부르는 구조이다. 그런데 c에서 checked 예외를 던지게 되면 a,b에서는 모두 예외를 잡기 위해 `throws`를 붙혀줘야 한다.

물론 처음 코드를 작성할 때 throws를 작성했으면 괜찮을 수 있다. 하지만 추후에 소스 수정이 일어나서 c에 다른 checked 예외를 추가하게 된다면 또 a,b에 예외 처리를 추가해야 한다. 이는 [OCP(Open-Closed Principle)](https://inpa.tistory.com/entry/OOP-%F0%9F%92%A0-%EC%95%84%EC%A3%BC-%EC%89%BD%EA%B2%8C-%EC%9D%B4%ED%95%B4%ED%95%98%EB%8A%94-OCP-%EA%B0%9C%EB%B0%A9-%ED%8F%90%EC%87%84-%EC%9B%90%EC%B9%99)에 위반한다.

#### Unchecked Exception

- RuntimeException을 상속하는 클래스
- 런타임 단계에서 확인 가능
- 에러 처리를 강제하지 않는다

Checked Exception과 다르게 컴파일 시 컴파일러에서 확인하지 않는 예외이다. 대표적으로 `NullPointerException`,`ArrayIndexOutOfBoundsException`이 Unchecked Exception에 해당한다.

```java
public class UncheckedException {
  public static void main(String[] args) {
    int[] numbers = { 1, 2, 3 };
    int index = 10;
    System.out.println('number = ' + numbers[index]);
  }
}
```

길이가 3인 numbers에 index가 10인 원소를 가져오려고 하는 코드이다. 당연하게도 `ArrayIndexOutOfBoundsException` 에러가 발생하는 코드이다.

마찬가지로 위의 코드도 try-catch를 사용해서 예외처리를 해줄 수 있다.

```java
public class UncheckedException {
    public static void main(String[] args) {
        int[] numbers = {1, 2, 3};
        int index = 10;

        try {
            int number = numbers[index];
            System.out.println("number = " + number);
        } catch (ArrayIndexOutOfBoundsException e) {
            System.out.println("An error occurred: " + e.getMessage());
        }
    }
}
```

그래서 간단하게 정리해보면 Checked Exception은 예외처리를 반드시 해줘야 하며, Unchecked Exception은 코드에 개발자가 예상치 못한 에러가 발생할 수 있기 때문에 예외처리를 강제하지 않는다는 것이다.

<br>

### 예외에 의미를 제공해라.

소스 전체에서 이상한 인자를 받는 예외 로직에 `IllegalArgumentException`만 발생시킨다면 어디서 에러가 발생했는지 stacktrace를 봐야만 알 수 있다.

추가로 IllegalArgumentException와 같이 자바에서 직접 제공해주는 예외를 사용하게 된다면 다른 로직에서 발생했는지 내 로직에서 발생했는지 알 수가 없다.

**따라서 우리는 오류 메세지에 정보를 담아서 예외와 함께 던지도록 하자. 실패한 연산 이름과 실패 유형도 언급하고 애플리케이션이 로깅 기능을 사용한다면 catch 블록에서 오류를 기록하도록 충분한 정보를 넘겨주면 좋을 것 같다.**

<br>

### 호출자를 고려해서 예외 클래스를 정의해라.

```java
ACMEPort port = new ACMEPort(12);

try {
  port.open();
} catch (DeviceResponseException e) {
  reportPortError(e);
  logger.log('Device response exception', e);
} catch (ATM1212UnlockedException e) {
    reportPortError(e);
    logger.log("Unlock response exception", e);
} catch (GMXError e) {
    reportPortError(e);
    logger.log("Device response exception", e);
} finally {
    ...
}
```

위에서 open 메서드는 3개의 에러를 발생시키고 있다. 그래서 우리는 try-catch를 필수로 작성해야만 한다. 그래서 우리는 wrapper 클래스를 이용해서 리팩터링을 할 수 있을 것 같다.

```java
public class LocalPort {
  private ACMEPort innerPort;

  public LocalPort(ACMEPort innerPort) {
    this.innerPort = innerPort;
  }

  public void open() {
    try {
      innerPort.open();
    } catch (DeviceResponseException e) {
      throw new PortDeviceFailure(e);
    } catch (ATM1212UnlockedException e) {
      throw new PortDeviceFailure(e);
    } ...
  }
}
```

위와 같이 3개의 예외를 `PortDeviceFailure`로 통일시켜서 처리하는 LocalPort 클래스를 만들어서 더욱 깨끗하게 코드를 작성했다.

**따라서 우리는 예외 처리 로직이 많은 경우에는 호출자를 고려해서 wrapper 클래스로 깔끔하게 사용해보자.**

<br>

### 정상 흐름을 정의해라.

```java
public UserLevel getUserLevel(Long id) {
  try {
    User user = userRepository.findById(id);
    return user.getLevel();
  } catch (UserNotFoundException e) {
    return UserLevel.BASIC;
  }
}
```

id로 user를 가지고 와서 level 값을 반환해주는 코드이다. 그리고 에러가 발생하면 UserLevel에 BASIC을 넣어준다. user를 id로 찾아와서 있으면 getLevel을 없으면 BASIC을 리턴하라는 로직인데 try-catch로 되어 있어서 코드를 이해하는데 방해를 한다.

```java
public UserLevel getUserLevelOrDefault(Long id) {
  User user = userRepository.findById(id);

  if (user == null) {
    return UserLevel.BASIC;
  } else {
    return user.getLevel();
  }
}
```

위와 같이 예외를 없애고 흐름에 따라 읽히게 사용하면 좋을 것 같다.

<br>

### null을 반환하지 마라.

내가 가장 고쳐야 할 부분이라고 생각한다... 이번 기회에 쫙 고쳐보자.

```java
List<Employee> employees = getEmployees();

if (employee != null) {
  for (Employee e : employee) {
    totalPay += e.getPay();
  }
}
```

위 코드에서 getEmployees가 null을 반환해서 if 구문이 생겼는데 굳이 null을 반환할 필요가 있을까?
Java에서는 null인 경우 Collections.emptyList()를 리턴해주도록 변경할 수 있을 것 같다.

```java
List<Employee> employees = getEmployees();

for(Employee e : employees) {
    totalPay += e.getPay();
}
```

그렇게 되면 굳이 if 구문을 추가하지 않아도 되고, NullPointerException이 발생할 가능성도 줄어들었다.

<br>

### null을 전달하지 말자.

이것도 마찬가지..

```java
public double xProjection(Point p1, Point p2) {
  return (p2.x - p1.x) * 1.5;
}
```

위의 코드는 두 지점 사이의 거리를 구하는 메서드이다. 위 메서드를 `calculator.xProjection(null, new Point(12, 13))`로 호출하면 어떻게 되나? 당연히 `NPE`가 발생한다.

```java
public double xProjection(Point p1, Point p2) {
  if (p1 == null || p2 == null) {
    throw InvalidArgumentException("--");
  }
  return (p2.x - p1.x) * 1.5;
}
```

위처럼 null을 체크하면 예외처리를 할 수 있다. 이쁘지는 않지만 필요해 보이는 로직이긴 하다.
따라서 null을 넘기면 에러가 발생할 확률이 많아지기 때문에 아예 넘겨버리지 않는 것이 제일좋다.

---

### Reference

- https://effortguy.tistory.com/190
- https://inpa.tistory.com/entry/OOP-%F0%9F%92%A0-%EC%95%84%EC%A3%BC-%EC%89%BD%EA%B2%8C-%EC%9D%B4%ED%95%B4%ED%95%98%EB%8A%94-OCP-%EA%B0%9C%EB%B0%A9-%ED%8F%90%EC%87%84-%EC%9B%90%EC%B9%99
